export const FilterCategories = [
  {
    name: "Mobile",
    char1: "Screen Size (inches)",
    char2: "RAM (GB)",
    char3: "Drive Capacity (GB)",
    char4: "Battery Capacity (mAh)",
    char5: "Camera (MP)",
    char6: "Processor",
    char7: "OS",
    char8: "Color",
    price: "Price",
  },
  {
    name: "Laptop",
    char1: "Processor Brand",
    char2: "Processor Model",
    char3: "Processor Speed",
    char4: "RAM Type",
    char5: "GPU",
    char6: "Display Size (inches)",
    char7: "Resolution (px)",
    char8: "Color",
    price: "Price",
  },
  {
    name: "Tablet",
    char1: "Screen Size (inches)",
    char2: "RAM (GB)",
    char3: "Drive Capacity (GB)",
    char4: "Battery Capacity (mAh)",
    char5: "Camera (MP)",
    char6: "Processor",
    char7: "OS",
    char8: "Color",
    price: "Price",
  },
  {
    name: "Audio",
    char1: "Main Function",
    char2: "Battery Capacity (mAh)",
    char3: "Color",
    char4: "Connection Type",
    char5: "Device Type",
    price: "Price",
  },
  {
    name: "Wearable",
    char1: "Display Type",
    char2: "GPS",
    char3: "Health Monitoring",
    char4: "Battery Life (mAh)",
    char5: "Water Resistance",
    char6: "Operating System",
    char7: "Connectivity",
    char8: "Color",
    price: "Price",
  },
  {
    name: "Camera",
    char1: "Sensor Type",
    char2: "Autofocus System",
    char3: "Video Resolution",
    char4: "Battery Capacity (mAh)",
    char5: "Image Stabilization",
    char6: "Lens Mount",
    char7: "Connectivity",
    char8: "Color",
    price: "Price",
  },
  {
    name: "Gaming",
    char1: "Product Type",
    char2: "Features",
    char3: "Technology/Specs",
    char4: "Special Features",
    price: "Price",
  },
  {
    name: "Network",
    char1: "Wi-Fi Standard",
    char2: "Speeds (Mbps)",
    char3: "Ethernet Ports",
    char4: "Mesh System",
    char5: "Smart Home Support",
    char6: "Security Features",
    char7: "Color",
    price: "Price",
  },
];
